### ISSUE TITLE
valid message buffer python change

### ISSUE THREAD

**Issue by caseyjlaw** [mpokorny/vysmaw#23]
I am working on a vysmaw application via Python and it seems that the valid message buffer API has changed around here: https://github.com/mpokorny/vysmaw/blob/master/py/cy_vysmaw.pyx#L543.
The property was called "buffer" but is now "spectrum". If I update my application for that new syntax, it still stumbles over the "buffer_size" property.
Perhaps some new feature got merged during recent changes?

**Comment by mpokorny** [comment]
The change from "buffer" to "spectrum" occurred because the content of a buffer has been changed in vys version 3 to include a sequence number. Since only the spectral data, and not the sequence number, is of interest to vysmaw application code, the field referring to the spectral data was renamed "spectrum". The "buffer_size" property was removed as it could be mistaken to refer to the spectrum size or length. The spectrum size is now implicit in the length of the vector returned by the "spectrum" property. Nevertheless, I see now that the code in https://github.com/mpokorny/vysmaw/blob/fb089937716371d5926a52b8f9023959e27d4a26/py/cy_vysmaw.pyx#L544 appears to incorrectly reference "self.buffer_size" in class ValidBufferMessage.

**Comment by mpokorny** [comment]
Casey, if you're using vysmaw installed on the CBE cluster, I've just updated it to provide the "spectrum" property correctly, from commit https://github.com/mpokorny/vysmaw/commit/5a7b871c32200389e35ebb16db5938a2aeba4b06. I've not tested this, so please let me know if the commit solves this issue.

**Comment by caseyjlaw** [comment]
That's fixed it. Thanks.
