### ISSUE TITLE
python 3.6 builds needed

### ISSUE THREAD

**Issue by caseyjlaw** [mpokorny/vysmaw#31]
I am working toward python 2/3 compatibility. I think I have all the major pieces in place.
One missing piece is that I cannot compile vysmaw applications in python 3.6.
I see the `setup.py` file has this path set for some libraries:
`/home/cbe-master/wcbe/py/lib/python2.7/site-packages/vysmaw`. And using it to compile my python 3.6 version does leads to issues.
Any chance you could build the vysmaw libraries with python3.6. I have a version on the CBE at `~claw/anaconda/envs/development3/bin/python`.

**Comment by mpokorny** [comment]
This is a CBE environment issue, I think. I will have to get one of the sysadmins to install python 3.6 on the CBE, probably under /home/cbe-master/wcbe/py/lib/python3.6, and then I can rebuild vysmaw against that. I believe that at one time, for testing, I did build vysmaw against python3, so I'm optimistic that it will work again. We have not generally migrated to python 3.6 on the CBE, but it's probably OK for libvysmaw since realfast is the only user of that software, and the wcbe software doesn't use vysmaw. I don't want a library installed system-wide to depend on the version of python3.6 installed in your home directory, however. I'm going to close this issue, as it isn't a vysmaw issue, per se.

**Comment by caseyjlaw** [comment]
Sounds good. Thanks for looking into it.
