### ISSUE TITLE
vysmaw2 message validation

### ISSUE THREAD

**Issue by caseyjlaw** [mpokorny/vysmaw#41]
My client is crashing in some high data rate tests I am running. I noticed that the crashes tend to happen when I see VYSMAW_MESSAGE_QUEUE_ALERT messages. I suspect that my client is falling behind and not reading data in time.
I have notes in my code about how to validate data before reading. However, I have not implemented them. These three are suggested in my notes:
- msg[0].data[i].failed_verification is False
- len(msg[0].data[i].values) > 0
- msg[0].data[i].rdma_read_status == ""

If I failed to run these checks, is it possible to crash a vysmaw client?

**Comment by mpokorny** [comment]
You'll definitely need to implement the second test in your list. Failure to do so could certainly result in a crash if you try to read even one value from the spectrum. Failing to do the other tests may result in your code getting bad data, but it's also possible that the second case is false when either of the other two are (I could get you a definitive answer by reading the code, but it seems like something I'd do -- i.e, either provide good data or no data at all).

**Comment by caseyjlaw** [comment]
If you have time, it would be nice to confirm that. I'm having some trouble reproducing some errors when using vyssim, but I'll need to rely on that more given that test time is short these days.

**Comment by mpokorny** [comment]
I can confirm that if `msg[0].data[i].failed_verification is True`, or `msg[0].data[i].rdma_read_status != ""`, then `len(msg[0].data[i].values) == 0`.

**Comment by caseyjlaw** [comment]
Ok, thanks. I needed to get that to compile in cython with `nogil`. I can get it to compile this way:
```
if (msg[0].data[i].failed_verification is False) and (msg[0].data[i].rdma_read_status[0] is "\0"):
```
Is that equivalent?

**Comment by mpokorny** [comment]
Hmm, it's not the case that given the condition you quote, it is necessarily true that the `values` array has non-zero length. There is at least one other case (a canceled RDMA request) that can have a similar outcome. If you're not interested in the reason for the failure to acquire the spectrum, you can simply test the length of the `values` array and skip the other tests.

**Comment by caseyjlaw** [comment]
What would you do to test the length of the array in C? If I use python `len(msg[0].data[i].values)` then I get into issues with the Python GIL.

**Comment by mpokorny** [comment]
`msg[0].data[i].values` returns a cython view array object with zero elements. I'm not sure what you can do with it without locking the GIL, but the answer may be in the cython documentation. You might try this test `msg[0].data[i].values.shape[0] > 0`...but I haven't tried it, and I'm not entirely certain that it doesn't need the GIL.

**Comment by caseyjlaw** [comment]
I think I'll fall back to the original test and hold the GIL. So:
```
if (msg[0].data[i].failed_verification is False) and (msg[0].data[i].rdma_read_status == b""):
```

If I simulate a 10 ms, full S-band mode, I get 2 Mmsg/s and start to see some queue underflow messages and invalid spectra are reported in the client.
Unfortunately, I am still getting some segfaults, so something isn't quite right. I'll keep playing.

**Comment by mpokorny** [comment]
If the segfaults are occurring near the time that your app shuts down the vysmaw handle, RDMA requests could be getting canceled, and then dereferencing the `values` array would be a problem.

On another note, are you using a single vyssim instance or multiple instances? It can be hard to sort out whether your app or vyssim is not able to keep up -- using multiple vyssim instances might change things. Also, if you're using random data from vyssim, that can definitely affect its performance.

**Comment by caseyjlaw** [comment]
The crash occurs during reading, not shut down. I am testing vyssim on one node with the -r flag. Can you remind me of how to run vyssim with mpi?
I recently added a test of whether the indexes I use in Python (a given integration, baseline, spectrum, pol) are being used more than once. In some cases, I get reports that a given index has already been read. That may be some error in how my client allocates memory or parses the spectrum. I'll keep digging.

**Comment by mpokorny** [comment]
To run vyssim with mpi:
`MV2_ENABLE_AFFINITY=0 mpirun_rsh -np <N> <host1> ... <hostN> vyssim <vyssim args>`

If you don't make progress on sorting out the indexes, I will write a simple test program in C++ that has a similar check of indexes to help determine whether the problem is in vysmaw, vysmaw cython code or your application.

**Comment by caseyjlaw** [comment]
Thanks, that adds some nuance to this issue.
If I run vyssim without mpirun_rsh I see occasional crashes when it falls behind. I infer it falls behind because I get `VYSMAW_MESSAGE_QUEUE_ALERT` messages and `msg[0].data[i].failed_verification == True`. However, it can often finish reading and return the data associated with valid messages.
If I run vyssim with with mpirun_rsh, it crashes every time. Curiously, it crashes sooner, after getting a few `VYSMAW_MESSAGE_QUEUE_ALERT` messages. However, I do not get any spectra with `failed_verification`.

I have not seen any spectra with `msg[0].data[i].rdma_read_status != b""`. Perhaps that's a red flag. It could be I'm not triggering the condition properly.

Any ideas?

**Comment by mpokorny** [comment]
The `VYSMAW_MESSAGE_QUEUE_ALERT` messages are caused by a large backlog in the message queue (from libvysmaw to your app). That will happen if the app is not keeping up with the rate at which messages are being placed on the queue. Not necessarily a bad thing for buffering message bursts, but it's unsustainable over longer periods. There's no hard limit to the queue size, but the message should be taken as a warning sign that the app isn't keeping up.

Here's one failure scenario that is roughly consistent with your observations. The app is not keeping up with removing messages from the message queue, thus buffers in the memory pool for RDMA transfers are also being exhausted, and consequently RDMA requests are being canceled. This results in getting empty `values` arrays, which the app dereferences, resulting in a crash. I really think you need a way to test whether the `values` array containing the spectral data has non-zero length before reading from it.

Have you played with the memory allocation configuration parameters at all? That can't change the long term outcome, but if the allocations are large enough to take in all the data you expect over the active time window, it would work (at least until the data rate goes up or the size of the time window increases).

It's also possible you're bumping up against the maximum bandwidth limit for the RDMA transfers. It's been a while since I did the tests, but maybe 2e6 messages/sec are near the limit. If you send me the parameters you're using with vyssim, I'll run a similar test using one of the C++ test apps.

**Comment by caseyjlaw** [comment]
Ok, thanks. This is the most demanding scenario I'm testing:
```
MV2_ENABLE_AFFINITY=0 mpirun_rsh -np 3 cbe-node-01 cbe-node-02 cbe-node-03 ~/anaconda/envs/development3/bin/vyssim -r -f 10 -a 27 -w 32 -c 32 -p 4 -i 10000 -v ~/soft/vysmaw_apps/vys.conf
```

I'll look into the length of `values`.

**Comment by caseyjlaw** [comment]
I am trying to do something simple with the values array, but am getting cython errors I don't understand. For example:
```
printf("%d\t", msg[0].data[i].values.shape[0])
```

when compiled gives this error:
```
vysmaw_reader.pyx:298:65: Cannot convert 'float complex *' to Python object
```

My understanding is that the `values` array should be a memoryview, not a pointer?
Assuming it is a pointer, I do not know how to check its length. All examples on using c pointers in cython describe creating an array of some sort (e.g., memoryview) with an explicit shape. If I assign the pointer to such an array, isn't it going to have the length I define (not that referenced by the pointer)?

**Comment by mpokorny** [comment]
The `values` array should be a memoryview. Guess I'll need to have a closer look at the vysmaw cython code.

**Comment by mpokorny** [comment]
I think the problem is that the `msg` you are using is an unwrapped message, meaning, not a python object, and thus none of its fields are python objects. This means that instead of testing the length of the `values` array, the value should be directly compared against NULL to decide whether or not the spectrum was successfully retrieved. As for the length of the `values` array, you'll have to compute that from the value of `msg[0].spectra.spectrum_buffer_size`, which is in bytes, not number of complex float elements. You probably already know how many channels there are in a spectrum, so you could just use that instead (vysmaw will never return a partial spectrum). If you want to access the spectrum through a cython or numpy array, your application will have to do that conversion itself, again because `msg` is only a pointer to a C struct. I could probably write a cython function to do that for you, if you'd find that useful.

**Comment by caseyjlaw** [comment]
Thanks, that's fixed it. Sorry for the silly error.
I'm now testing with:
```
if (msg[0].data[i].failed_verification is False) and (msg[0].data[i].values is not NULL):
```
and am seeing safe operation at the same levels as before. I still see the client fall behind and the occasional bad message types, but it does not come with a crash.
I'll close this issue.
